from tkinter import *
from PIL import Image, ImageTk
import tkinter.font as font
from tkinter import messagebox
class ViewPage():
    def __init__(self,root):
        self.root=root
        self.root.geometry("1200x720")
        self.root.state('normal')
        self.frame = Frame(self.root)
        '''root.configure(background='green')'''
        self.frame.pack()
        self.var = StringVar()
        self.label = Label(self.frame, textvariable=self.var, fg="green")
        self.label.config(width=150)
        self.label.config(font=("Courier", 45))
        self.var.set("WELCOME TO ALOKANAND CLINIC")
        self.label.pack()
        self.path = "icons/dispensary2.jpg"
        self.img = ImageTk.PhotoImage(Image.open(self.path))
        self.panel = Label(self.frame, image=self.img)
        self.panel.pack(side="left", fill="both")
        self.var1 = StringVar()
        self.label1 = Label(self.frame, textvariable=self.var1, fg="black")
        self.label1.config(width=100)
        self.label1.config(font=("Courier", 15, 'italic'))
        self.var1.set("\"It is health that is real wealth and not")
        self.label1.pack()
        self.var2 = StringVar()
        self.label2 = Label(self.frame, textvariable=self.var2, fg="black")
        self.label2.config(width=100)
        self.label2.config(font=("Courier", 15, 'italic'))
        self.var2.set("pieces of Gold and Silver\"")
        self.label2.pack()
        self.var3 = StringVar()
        self.label3 = Label(self.frame, textvariable=self.var3, fg="black")
        self.label3.config(width=50)
        self.label3.config(font=("Courier", 15))
        self.var3.set("- Mahatma Gandhi")
        self.label3.place(x=750, y=125)
        self.var4 = StringVar()
        self.label4 = Label(self.frame, textvariable=self.var4, fg="black")
        self.label4.config(width=30)
        self.label4.config(font=("Courier", 25, 'bold'))
        self.var4.set("Dr.Harish Gagan Arora")
        self.label4.place(x=550, y=200)
        self.var5 = StringVar()
        self.label5 = Label(self.frame, textvariable=self.var5, fg="black")
        self.label5.config(width=30)
        self.label5.config(font=("Courier", 15))
        self.var5.set("- M.B.B.S,M.D")
        self.label5.place(x=850, y=250, anchor=NW)
        self.var6 = StringVar()
        self.label6 = Label(self.frame, textvariable=self.var6, fg="black")
        self.label6.config(width=50)
        self.label6.config(font=("Courier", 15))
        self.var6.set("ADDRESS:Shop no.121-B,OPP. Shiavji Garden,")
        self.label6.place(x=590, y=325)
        self.var7 = StringVar()
        self.label7 = Label(self.frame, textvariable=self.var7, fg="black")
        self.label7.config(width=50)
        self.label7.config(font=("Courier", 15))
        self.var7.set("M.G. Road,Ghatkopar(E)-400077")
        self.label7.place(x=590, y=350)
        self.var8 = StringVar()
        self.label8 = Label(self.frame, textvariable=self.var8, fg="black")
        self.label8.config(width=50)
        self.label8.config(font=("Courier", 15))
        self.var8.set("Contact us at:+022-2518964,+022-2518965")
        self.label8.place(x=590, y=400)
        self.var9 = StringVar()
        self.label9 = Label(self.frame, textvariable=self.var9, fg="black")
        self.label9.config(width=50)
        self.label9.config(font=("Courier", 15))
        self.var9.set("For any further help you can reach us")
        self.label9.place(x=590, y=450)
        self.var10 = StringVar()
        self.label10 = Label(self.frame, textvariable=self.var10, fg="black")
        self.label10.config(width=30)
        self.label10.config(font=("Courier", 15))
        self.var10.set("at alokanandclinic@gmail.com")
        self.label10.place(x=690, y=475)
        self.myFont = font.Font(family='Helvetica', size=20, weight='bold', slant='italic')
        self.B1 = Button(self.frame, text="Doctor", bd='5', bg='#0052cc', fg='#ffffff', command=self.login)
        self.B1['font'] = self.myFont
        self.B1.place(x=690, y=580)
        self.B2 = Button(self.frame, text="Patient", bd='5', bg='#0052cc', fg='#ffffff', command=self.register)
        self.B2['font'] = self.myFont
        self.B2.place(x=900, y=580)
        self.footer = Label(self.frame, bg="ivory3", height=1, text="@Copyright 2020 Alokanand. All rights reserved")
        self.footer.pack(side=BOTTOM, fill=X)
        self.panel.pack_propagate(0)

    def register(self):
        import RegisterationPage
        self.frame.destroy()
        RegisterationPage.Register(self.root)

    def login(self):
        login_window=Toplevel()
        login_window.title("Registeration")
        login_window.geometry("700x400")
        login_window.resizable(False, False)
        self.login_frame=Frame(login_window,height=500)
        self.login_frame.pack(fill=X)
        self.register_icon = PhotoImage(file='icons/blood-pressure.png')
        self.icon_label = Label(self.login_frame, image=self.register_icon)
        self.icon_label.place(x=220, y=30)
        self.home_icon = PhotoImage(file='icons/home-run.png')
        self.top_label = Label(self.login_frame, text="Login", font=('arial bold 16', 30))
        self.top_label.place(x=290, y=40)
        self.l_login = Label(self.login_frame, text='Login ID', font=('arial'))
        self.l_password = Label(self.login_frame, text='Password', font=('arial'))
        self.e_login = Entry(self.login_frame, width=30, bg='white', fg='black', font=('arial'))
        self.e_password = Entry(self.login_frame, width=30, bg='white', fg='black', font=('arial'), show='*')
        self.l_login.place(x=100, y=140)
        self.l_password.place(x=100, y=240)
        self.e_login.place(x=240, y=140)
        self.e_password.place(x=240, y=240)
        self.submit = Button(self.login_frame, text='Submit', bg='#ebe6d8', padx=20, font=('arial'), command=lambda: self.view(login_window))
        self.submit.place(x=540, y=340)
        self.home_icon = PhotoImage(file='icons/home-run.png')
        #self.home_button = Button(self.login_frame, image=self.home_icon, command=self.Homepage, bg='#ebe6d8', padx=20,
                                  #font=('arial'))
        #self.home_button.place(x=570, y=10)

    def view(self,login_window):
        login = self.e_login.get()
        password = self.e_password.get()
        if login == 'Girish' and password == '123456789':
            login_window.destroy()
            self.frame.destroy()
            import DoctorPage
            DoctorPage.DoctorPage(self.root)

        else:
            messagebox.showwarning('Incorrect credentials',
                                   'The username and password entered does not match. Please re-enter')
            self.e_login.delete(0,END)
            self.e_password.delete(0,END)
            login_window.tkraise()

if __name__=="__main__":
    root=Tk()
    ViewPage(root)
    root.mainloop()